spring:
  application:
    name: spring-aws-iot-training

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:h2:file:./db
    driverClassName: org.h2.Driver
    username: sa
    password: password

  h2:
    console:
      enabled: true

config:
  aws:
    account: 459293086294
    region: us-east-1

logging:
  level:
    org:
      springframework:
        security: DEBUG

application:
  users:
    - username: admin
      password: admin
      authorities: READ,WRITE
    - username: user
      password: user
      authorities: READ
    - username: nope
      password: nope

#RBAC = Role based <- this for the example
#ReBAC = Relation based
#ABAC = Attribute based